flowchart TD
    DependencyInjectorLayer-->DeviceFramework
    DependencyInjectorLayer-->FirebaseFramework
    DependencyInjectorLayer-->LicenseFramework
    DependencyInjectorLayer-->PresentationLayer
    DeviceFramework-->DomainLayer
    DomainLayer
    FirebaseFramework-->DomainLayer
    FrameworkTest{{FrameworkTest}}-->DeviceFramework
    FrameworkTest{{FrameworkTest}}-->FirebaseFramework
    FrameworkTest{{FrameworkTest}}-->LicenseFramework
    InteractorTest{{InteractorTest}}-->DependencyInjectorLayer
    LicenseFramework-->DomainLayer
    PresentationLayer-->DomainLayer
    PresenterTest{{PresenterTest}}-->PresentationLayer
    PreviewCatalogLayer-->PresentationLayer
