///
/// @Generated by Mockolo
///



import Combine
import DomainLayer
import Foundation
import SwiftUI


public final class AppRootRouterDependencyMock: AppRootRouterDependency {
    public init() { }
    public init(cacheDataStore: CacheDataStoreProtocolAT, logDriver: LogDriverProtocolAT, libraryLicenseDriver: LibraryLicenseDriverProtocolAT, buildEnvDriver: BuildEnvDriverProtocolAT, deviceInfoDriver: DeviceInfoDriverProtocolAT, clipboardDriver: ClipboardDriverProtocolAT) {
        self._cacheDataStore = cacheDataStore
        self._logDriver = logDriver
        self._libraryLicenseDriver = libraryLicenseDriver
        self._buildEnvDriver = buildEnvDriver
        self._deviceInfoDriver = deviceInfoDriver
        self._clipboardDriver = clipboardDriver
    }

    public typealias CacheDataStoreProtocolAT = CacheDataStoreProtocolMock
    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var cacheDataStoreSetCallCount = 0
    private var _cacheDataStore: CacheDataStoreProtocolAT!  { didSet { cacheDataStoreSetCallCount += 1 } }
    public var cacheDataStore: CacheDataStoreProtocolAT {
        get { return _cacheDataStore }
        set { _cacheDataStore = newValue }
    }
    public typealias LibraryLicenseDriverProtocolAT = LibraryLicenseDriverProtocolMock

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
    public typealias BuildEnvDriverProtocolAT = BuildEnvDriverProtocolMock

    public private(set) var libraryLicenseDriverSetCallCount = 0
    private var _libraryLicenseDriver: LibraryLicenseDriverProtocolAT!  { didSet { libraryLicenseDriverSetCallCount += 1 } }
    public var libraryLicenseDriver: LibraryLicenseDriverProtocolAT {
        get { return _libraryLicenseDriver }
        set { _libraryLicenseDriver = newValue }
    }
    public typealias DeviceInfoDriverProtocolAT = DeviceInfoDriver<DeviceNameDriverProtocolMock>
    public typealias ClipboardDriverProtocolAT = ClipboardDriver

    public private(set) var buildEnvDriverSetCallCount = 0
    private var _buildEnvDriver: BuildEnvDriverProtocolAT!  { didSet { buildEnvDriverSetCallCount += 1 } }
    public var buildEnvDriver: BuildEnvDriverProtocolAT {
        get { return _buildEnvDriver }
        set { _buildEnvDriver = newValue }
    }

    public private(set) var deviceInfoDriverSetCallCount = 0
    private var _deviceInfoDriver: DeviceInfoDriverProtocolAT!  { didSet { deviceInfoDriverSetCallCount += 1 } }
    public var deviceInfoDriver: DeviceInfoDriverProtocolAT {
        get { return _deviceInfoDriver }
        set { _deviceInfoDriver = newValue }
    }

    public private(set) var clipboardDriverSetCallCount = 0
    private var _clipboardDriver: ClipboardDriverProtocolAT!  { didSet { clipboardDriverSetCallCount += 1 } }
    public var clipboardDriver: ClipboardDriverProtocolAT {
        get { return _clipboardDriver }
        set { _clipboardDriver = newValue }
    }
}

public final class DeviceInfoPresenterDependencyMock: DeviceInfoPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT, buildEnvDriver: BuildEnvDriverProtocolAT, deviceInfoDriver: DeviceInfoDriverProtocolAT, clipboardDriver: ClipboardDriverProtocolAT) {
        self._logDriver = logDriver
        self._buildEnvDriver = buildEnvDriver
        self._deviceInfoDriver = deviceInfoDriver
        self._clipboardDriver = clipboardDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
    public typealias BuildEnvDriverProtocolAT = BuildEnvDriverProtocolMock
    public typealias DeviceInfoDriverProtocolAT = DeviceInfoDriver<DeviceNameDriverProtocolMock>
    public typealias ClipboardDriverProtocolAT = ClipboardDriver

    public private(set) var buildEnvDriverSetCallCount = 0
    private var _buildEnvDriver: BuildEnvDriverProtocolAT!  { didSet { buildEnvDriverSetCallCount += 1 } }
    public var buildEnvDriver: BuildEnvDriverProtocolAT {
        get { return _buildEnvDriver }
        set { _buildEnvDriver = newValue }
    }

    public private(set) var deviceInfoDriverSetCallCount = 0
    private var _deviceInfoDriver: DeviceInfoDriverProtocolAT!  { didSet { deviceInfoDriverSetCallCount += 1 } }
    public var deviceInfoDriver: DeviceInfoDriverProtocolAT {
        get { return _deviceInfoDriver }
        set { _deviceInfoDriver = newValue }
    }

    public private(set) var clipboardDriverSetCallCount = 0
    private var _clipboardDriver: ClipboardDriverProtocolAT!  { didSet { clipboardDriverSetCallCount += 1 } }
    public var clipboardDriver: ClipboardDriverProtocolAT {
        get { return _clipboardDriver }
        set { _clipboardDriver = newValue }
    }
}

public final class HomeTabPresenterDependencyMock: HomeTabPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT) {
        self._logDriver = logDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class SettingPresenterDependencyMock: SettingPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT) {
        self._logDriver = logDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class TaskListPresenterDependencyMock: TaskListPresenterDependency {
    public init() { }
    public init(cacheDataStore: CacheDataStoreProtocolAT, logDriver: LogDriverProtocolAT) {
        self._cacheDataStore = cacheDataStore
        self._logDriver = logDriver
    }

    public typealias CacheDataStoreProtocolAT = CacheDataStoreProtocolMock
    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var cacheDataStoreSetCallCount = 0
    private var _cacheDataStore: CacheDataStoreProtocolAT!  { didSet { cacheDataStoreSetCallCount += 1 } }
    public var cacheDataStore: CacheDataStoreProtocolAT {
        get { return _cacheDataStore }
        set { _cacheDataStore = newValue }
    }

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class CacheDataStoreProtocolMock: CacheDataStoreProtocol {
    public init() { }
    public init(remoteConfigUpdateErrorSubjecter: PassthroughSubject<AppError, Never>, appInfoSubjecter: CurrentValueSubject<AppInfo, Never>, variantTestSubjecter: CurrentValueSubject<VariantTest, Never>) {
        self._remoteConfigUpdateErrorSubjecter = remoteConfigUpdateErrorSubjecter
        self._appInfoSubjecter = appInfoSubjecter
        self._variantTestSubjecter = variantTestSubjecter
    }


    public private(set) var remoteConfigUpdateErrorSubjecterSetCallCount = 0
    private var _remoteConfigUpdateErrorSubjecter: PassthroughSubject<AppError, Never>!  { didSet { remoteConfigUpdateErrorSubjecterSetCallCount += 1 } }
    public var remoteConfigUpdateErrorSubjecter: PassthroughSubject<AppError, Never> {
        get { return _remoteConfigUpdateErrorSubjecter }
        set { _remoteConfigUpdateErrorSubjecter = newValue }
    }

    public private(set) var appInfoSubjecterSetCallCount = 0
    private var _appInfoSubjecter: CurrentValueSubject<AppInfo, Never>!  { didSet { appInfoSubjecterSetCallCount += 1 } }
    public var appInfoSubjecter: CurrentValueSubject<AppInfo, Never> {
        get { return _appInfoSubjecter }
        set { _appInfoSubjecter = newValue }
    }

    public private(set) var variantTestSubjecterSetCallCount = 0
    private var _variantTestSubjecter: CurrentValueSubject<VariantTest, Never>!  { didSet { variantTestSubjecterSetCallCount += 1 } }
    public var variantTestSubjecter: CurrentValueSubject<VariantTest, Never> {
        get { return _variantTestSubjecter }
        set { _variantTestSubjecter = newValue }
    }
}

public final class BuildEnvDriverProtocolMock: BuildEnvDriverProtocol {
    public init() { }
    public init(buildScheme: BuildScheme, buildConfiguration: BuildConfiguration) {
        self._buildScheme = buildScheme
        self._buildConfiguration = buildConfiguration
    }


    public private(set) var buildSchemeSetCallCount = 0
    private var _buildScheme: BuildScheme!  { didSet { buildSchemeSetCallCount += 1 } }
    public var buildScheme: BuildScheme {
        get { return _buildScheme }
        set { _buildScheme = newValue }
    }

    public private(set) var buildConfigurationSetCallCount = 0
    private var _buildConfiguration: BuildConfiguration!  { didSet { buildConfigurationSetCallCount += 1 } }
    public var buildConfiguration: BuildConfiguration {
        get { return _buildConfiguration }
        set { _buildConfiguration = newValue }
    }
}

public final class ClipboardDriverProtocolMock: ClipboardDriverProtocol {
    public init() { }
    public init(copiedValue: String? = nil) {
        self.copiedValue = copiedValue
    }


    public private(set) var copiedValueSetCallCount = 0
    public var copiedValue: String? = nil { didSet { copiedValueSetCallCount += 1 } }

    public private(set) var copyCallCount = 0
    public var copyHandler: ((String) -> ())?
    public func copy(_ string: String)  {
        copyCallCount += 1
        if let copyHandler = copyHandler {
            copyHandler(string)
        }
        
    }
}

public final class CommonPresenterDependencyMock: CommonPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT) {
        self._logDriver = logDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class DeviceInfoUseCaseDependencyMock: DeviceInfoUseCaseDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT, buildEnvDriver: BuildEnvDriverProtocolAT, deviceInfoDriver: DeviceInfoDriverProtocolAT) {
        self._logDriver = logDriver
        self._buildEnvDriver = buildEnvDriver
        self._deviceInfoDriver = deviceInfoDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
    public typealias BuildEnvDriverProtocolAT = BuildEnvDriverProtocolMock
    public typealias DeviceInfoDriverProtocolAT = DeviceInfoDriver<DeviceNameDriverProtocolMock>

    public private(set) var buildEnvDriverSetCallCount = 0
    private var _buildEnvDriver: BuildEnvDriverProtocolAT!  { didSet { buildEnvDriverSetCallCount += 1 } }
    public var buildEnvDriver: BuildEnvDriverProtocolAT {
        get { return _buildEnvDriver }
        set { _buildEnvDriver = newValue }
    }

    public private(set) var deviceInfoDriverSetCallCount = 0
    private var _deviceInfoDriver: DeviceInfoDriverProtocolAT!  { didSet { deviceInfoDriverSetCallCount += 1 } }
    public var deviceInfoDriver: DeviceInfoDriverProtocolAT {
        get { return _deviceInfoDriver }
        set { _deviceInfoDriver = newValue }
    }
}

public final class DeviceInfoUseCaseMock: DeviceInfoUseCase {
    public init() { }


    public private(set) var getDeviceInfoValueCallCount = 0
    public var getDeviceInfoValueHandler: ((DeviceInfoType) -> (String))?
    public func getDeviceInfoValue(_ deviceInfoType: DeviceInfoType) -> String {
        getDeviceInfoValueCallCount += 1
        if let getDeviceInfoValueHandler = getDeviceInfoValueHandler {
            return getDeviceInfoValueHandler(deviceInfoType)
        }
        return ""
    }
}

public final class DeviceNameDriverProtocolMock: DeviceNameDriverProtocol {
    public init() { }
    public init(deviceName: String = "") {
        self.deviceName = deviceName
    }


    public private(set) var deviceNameSetCallCount = 0
    public var deviceName: String = "" { didSet { deviceNameSetCallCount += 1 } }
}

public final class FirebaseLogDriverProtocolMock: FirebaseLogDriverProtocol {
    public init() { }


    public private(set) var logCallCount = 0
    public var logHandler: ((LogEventType, LogLevel, String, String, Int) -> ())?
    public func log(_ _arg: LogEventType, level: LogLevel, file: String, function: String, line: Int)  {
        logCallCount += 1
        if let logHandler = logHandler {
            logHandler(_arg, level, file, function, line)
        }
        
    }
}

public final class FirebaseRemoteConfigDriverProtocolMock: FirebaseRemoteConfigDriverProtocol {
    public init() { }


}

public final class FirebaseSetupDriverProtocolMock: FirebaseSetupDriverProtocol {
    public init() { }


}

public final class LibraryLicenseDriverProtocolMock: LibraryLicenseDriverProtocol {
    public init() { }
    public init(licenseList: [License] = [License]()) {
        self.licenseList = licenseList
    }


    public private(set) var licenseListSetCallCount = 0
    public var licenseList: [License] = [License]() { didSet { licenseListSetCallCount += 1 } }
}

public final class LogDriverDependencyMock: LogDriverDependency {
    public init() { }
    public init(osLogDriver: OSLogDriverProtocolAT, firebaseLogDriver: FirebaseLogDriverProtocolAT) {
        self._osLogDriver = osLogDriver
        self._firebaseLogDriver = firebaseLogDriver
    }

    public typealias OSLogDriverProtocolAT = OSLogDriver
    public typealias FirebaseLogDriverProtocolAT = FirebaseLogDriverProtocolMock

    public private(set) var osLogDriverSetCallCount = 0
    private var _osLogDriver: OSLogDriverProtocolAT!  { didSet { osLogDriverSetCallCount += 1 } }
    public var osLogDriver: OSLogDriverProtocolAT {
        get { return _osLogDriver }
        set { _osLogDriver = newValue }
    }

    public private(set) var firebaseLogDriverSetCallCount = 0
    private var _firebaseLogDriver: FirebaseLogDriverProtocolAT!  { didSet { firebaseLogDriverSetCallCount += 1 } }
    public var firebaseLogDriver: FirebaseLogDriverProtocolAT {
        get { return _firebaseLogDriver }
        set { _firebaseLogDriver = newValue }
    }
}

public final class LogDriverProtocolMock: LogDriverProtocol {
    public init() { }


    public private(set) var logCallCount = 0
    public var logHandler: ((LogEventType, LogLevel, String, String, Int) -> ())?
    public func log(_ _arg: LogEventType, level: LogLevel, file: String, function: String, line: Int)  {
        logCallCount += 1
        if let logHandler = logHandler {
            logHandler(_arg, level, file, function, line)
        }
        
    }
}

public final class LogDriverProviderMock: LogDriverProvider {
    public init() { }
    public init(logDriver: LogDriverProtocolAT) {
        self._logDriver = logDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class AppRootPresenterDependencyMock: AppRootPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT) {
        self._logDriver = logDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class LicenseDetailPresenterDependencyMock: LicenseDetailPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT) {
        self._logDriver = logDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }
}

public final class LicenseListPresenterDependencyMock: LicenseListPresenterDependency {
    public init() { }
    public init(logDriver: LogDriverProtocolAT, libraryLicenseDriver: LibraryLicenseDriverProtocolAT) {
        self._logDriver = logDriver
        self._libraryLicenseDriver = libraryLicenseDriver
    }

    public typealias LogDriverProtocolAT = LogDriver<OSLogDriver, FirebaseLogDriverProtocolMock>
    public typealias LibraryLicenseDriverProtocolAT = LibraryLicenseDriverProtocolMock

    public private(set) var logDriverSetCallCount = 0
    private var _logDriver: LogDriverProtocolAT!  { didSet { logDriverSetCallCount += 1 } }
    public var logDriver: LogDriverProtocolAT {
        get { return _logDriver }
        set { _logDriver = newValue }
    }

    public private(set) var libraryLicenseDriverSetCallCount = 0
    private var _libraryLicenseDriver: LibraryLicenseDriverProtocolAT!  { didSet { libraryLicenseDriverSetCallCount += 1 } }
    public var libraryLicenseDriver: LibraryLicenseDriverProtocolAT {
        get { return _libraryLicenseDriver }
        set { _libraryLicenseDriver = newValue }
    }
}

public final class DeviceInfoDriverProtocolMock: DeviceInfoDriverProtocol {
    public init() { }
    public init(appVersion: String = "", appBuildNumber: String = "", deviceName: String = "", deviceIdentifier: String = "", isSimulator: Bool = false, isPreview: Bool = false, osType: String = "", osVersion: String = "", timezone: String = "", language: String = "") {
        self.appVersion = appVersion
        self.appBuildNumber = appBuildNumber
        self.deviceName = deviceName
        self.deviceIdentifier = deviceIdentifier
        self.isSimulator = isSimulator
        self.isPreview = isPreview
        self.osType = osType
        self.osVersion = osVersion
        self.timezone = timezone
        self.language = language
    }


    public private(set) var appVersionSetCallCount = 0
    public var appVersion: String = "" { didSet { appVersionSetCallCount += 1 } }

    public private(set) var appBuildNumberSetCallCount = 0
    public var appBuildNumber: String = "" { didSet { appBuildNumberSetCallCount += 1 } }

    public private(set) var deviceNameSetCallCount = 0
    public var deviceName: String = "" { didSet { deviceNameSetCallCount += 1 } }

    public private(set) var deviceIdentifierSetCallCount = 0
    public var deviceIdentifier: String = "" { didSet { deviceIdentifierSetCallCount += 1 } }

    public private(set) var isSimulatorSetCallCount = 0
    public var isSimulator: Bool = false { didSet { isSimulatorSetCallCount += 1 } }

    public private(set) var isPreviewSetCallCount = 0
    public var isPreview: Bool = false { didSet { isPreviewSetCallCount += 1 } }

    public private(set) var osTypeSetCallCount = 0
    public var osType: String = "" { didSet { osTypeSetCallCount += 1 } }

    public private(set) var osVersionSetCallCount = 0
    public var osVersion: String = "" { didSet { osVersionSetCallCount += 1 } }

    public private(set) var timezoneSetCallCount = 0
    public var timezone: String = "" { didSet { timezoneSetCallCount += 1 } }

    public private(set) var languageSetCallCount = 0
    public var language: String = "" { didSet { languageSetCallCount += 1 } }
}

