flowchart TD
    DependencyInjectorLayer-->DeviceFramework
    DependencyInjectorLayer-->FirebaseFramework
    DependencyInjectorLayer-->LicenseFramework
    DependencyInjectorLayer-->PresentationLayer
    DeviceFramework-->DeviceKit[[DeviceKit]]
    DeviceFramework-->DomainLayer
    DomainLayer
    FirebaseFramework-->DomainLayer
    FirebaseFramework-->FirebaseAnalytics[[FirebaseAnalytics]]
    FirebaseFramework-->FirebaseCrashlytics[[FirebaseCrashlytics]]
    FirebaseFramework-->FirebaseRemoteConfig[[FirebaseRemoteConfig]]
    FrameworkTest{{FrameworkTest}}-->DeviceFramework
    FrameworkTest{{FrameworkTest}}-->FirebaseFramework
    FrameworkTest{{FrameworkTest}}-->LicenseFramework
    FrameworkTest{{FrameworkTest}}-->Testing[[Testing]]
    InteractorTest{{InteractorTest}}-->DependencyInjectorLayer
    InteractorTest{{InteractorTest}}-->Testing[[Testing]]
    LicenseFramework-->DomainLayer
    PresentationLayer-->DomainLayer
    PresentationLayer-->PreviewSnapshots[[PreviewSnapshots]]
    PresenterTest{{PresenterTest}}-->PresentationLayer
    PresenterTest{{PresenterTest}}-->Testing[[Testing]]
    PreviewCatalogLayer-->PresentationLayer
    PreviewCatalogLayer-->PreviewGallery[[PreviewGallery]]
    ViewSnapshotTest{{ViewSnapshotTest}}-->PresentationLayer
    ViewSnapshotTest{{ViewSnapshotTest}}-->PreviewSnapshotsTesting[[PreviewSnapshotsTesting]]
