flowchart TD
    DependencyInjectorLayer-->DeviceFramework
    DependencyInjectorLayer-->FirebaseFramework
    DependencyInjectorLayer-->LicenseFramework
    DependencyInjectorLayer-->PresentationLayer
    DeviceFramework-->DeviceKit[[DeviceKit]]
    DeviceFramework-->DomainLayer
    DomainLayer
    FirebaseFramework-->DomainLayer
    FirebaseFramework-->FirebaseAnalytics[[FirebaseAnalytics]]
    FirebaseFramework-->FirebaseCrashlytics[[FirebaseCrashlytics]]
    FirebaseFramework-->FirebaseRemoteConfig[[FirebaseRemoteConfig]]
    LicenseFramework-->DomainLayer
    PresentationLayer-->DomainLayer
    PresentationLayer-->PreviewSnapshots[[PreviewSnapshots]]
    PreviewCatalogLayer-->PresentationLayer
