flowchart TD
    DependencyInjectorLayer-->DeviceFramework
    DependencyInjectorLayer-->FirebaseFramework
    DependencyInjectorLayer-->LicenseFramework
    DependencyInjectorLayer-->PresentationLayer
    DeviceFramework-->DomainLayer
    DomainLayer
    FirebaseFramework-->DomainLayer
    LicenseFramework-->DomainLayer
    PresentationLayer-->DomainLayer
