flowchart TD
    DependencyInjectionLayer-->DeviceFramework
    DependencyInjectionLayer-->FirebaseFramework
    DependencyInjectionLayer-->LicenseFramework
    DependencyInjectionLayer-->PresentationLayer
    DeviceFramework-->DomainLayer
    DomainLayer
    FirebaseFramework-->DomainLayer
    LicenseFramework-->DomainLayer
    PresentationLayer-->DomainLayer
