flowchart TD
    DependencyInjectionLayer-->DeviceFramework
    DependencyInjectionLayer-->FirebaseFramework
    DependencyInjectionLayer-->LicenseFramework
    DependencyInjectionLayer-->PresentationLayer
    DeviceFramework-->DomainLayer
    DomainLayer
    DriverTest{{DriverTest}}-->DeviceFramework
    DriverTest{{DriverTest}}-->FirebaseFramework
    DriverTest{{DriverTest}}-->LicenseFramework
    FirebaseFramework-->DomainLayer
    InteractorTest{{InteractorTest}}-->DependencyInjectionLayer
    LicenseFramework-->DomainLayer
    PresentationLayer-->DomainLayer
    PresenterTest{{PresenterTest}}-->PresentationLayer
    PreviewCatalogLayer-->PresentationLayer
